### ISSUE TITLE
PROPOSAL: helm scaffold

### ISSUE THREAD

**Issue by technosophos** [deis/helm#188]
One of the things that Helm sets out to do is expedite the development of Kuberntes manifest files. And we already provide several tools to help chart developers create new charts.

Perhaps we could add a `helm scaffold` set of commands that would provide bare-bones Kubernetes manifest files.

```
$ helm scaffold pod memcached.yaml
----> Generated empty pod spec in ./memcached.yaml
$ helm scaffold service memcached-service.yaml
----> Generated empty service spec in ./memcached-service.yaml
```

A basic pod would look something like this:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: memcached
  heritage: helm
spec:
  containers:
  - name: example
    image: ""
```

And we would do similar templates for RCs, services, secretes, namespaces, volumes, etc.

## Goals

Make building basic charts easier without cluttering the output of `helm create`

## Non-Goals

Supply a generic template system

## Cons

This does stretch helm a little more toward a development tool.
